// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // The Prisma CLI (migrate/studio/db pull) only ever uses this `url` -
    // point it at the direct (non-pooled) connection, since Supabase's
    // pooled connection can't reliably run schema migrations. The running
    // app connects separately (see src/lib/prisma.ts) using DATABASE_URL,
    // the pooled connection meant for normal queries.
    url: process.env["DIRECT_URL"],
  },
});
